export const ROUTE_NAMES = {
  chat: 'Chat',
  profile: 'Profile',
  authorization: 'Authorization',
  signup: 'Signup',
  uikit: 'UIKit',
  switches: 'switches',
  uikitButtons: 'buttons',
  uikitTags: 'tags',
  uikitDropdown: 'dropdown',
  uikitTabs: 'tabs',
  uikitDatePicker: 'date_picker',
  uikitSelects: 'selects',
  uikitInputs: 'inputs',
  uikitForm: 'form',
} as const
